@baseUrl = http://localhost:3003

### GET existing blogs
GET {{baseUrl}}/api/blogs

### POST a new blog
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

### GET all blogs after adding
GET {{baseUrl}}/api/blogs

###
DELETE {{baseUrl}}/api/blogs/6593d59754f0618421e9af0b
